### ISSUE TITLE
vimb crashing on tab completion of commands

### ISSUE THREAD

**Issue by crypt17** [fanglingsu/vimb#486] opened 2018-05-24 00:16 UTC
latest version compiled from git
version shows as 
vimb --version
vimb, version 3.1.0

### Steps to reproduce
when trying to autocomplete a command or set a variable from the commandline vimb crashes.
ie
:se f<tab>
### Expected behaviour
expand the current command or give a list of commands
### Actual behaviour
segfaults

**Comment by fanglingsu** [comment] 2018-05-24 19:17
@crypt17 Can you please provide the information from `vimb --bug-info`? I can't reproduce this issue. Can you provide a stack trace?

**Comment by crypt17** [comment] 2018-05-24 20:49
I ran gdb over the core and got the following which doesn't look that useful

gdb vimb core
GNU gdb (Debian 7.12-6+b2) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html
>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law. Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from vimb...(no debugging symbols found)...done.
[New LWP 20032]
[New LWP 20050]
[New LWP 20117]
[New LWP 20051]
[New LWP 20106]
[New LWP 18224]
[New LWP 20084]
[New LWP 20085]
[New LWP 20033]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `vimb'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0 __memmove_sse2_unaligned_erms () at
../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:371
371 ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file
or directory.
[Current thread is 1 (Thread 0x7ff3b1207ac0 (LWP 20032))]
(gdb)


Any suggestions?

**Comment by crypt17** [comment] 2018-05-26 04:36
vimb --bug-info
Commit:          3.1.0-26-g4e8c5b2
WebKit compile:  2.20.2
WebKit run:      2.20.2
GTK compile:     3.22.30
GTK run:         3.22.30
libsoup compile: 2.62.2
libsoup run:     2.62.2
Extension dir:   /usr/local/lib/vimb

**Comment by fanglingsu** [comment] 2018-05-28 19:55
@crypt17 You could compile vimb with debug symbols without installation and run it direct throught gdb to get a backtrace.
```
make clean
CFLAGS="-g -O0" make -j sandbox
env G_DEBUG=fatal-criticals gdb -ex run --args sandbox/usr/bin/vimb
```
This should stop execution on SIGSEGV and you can obtain the backtrache via `bt` or `bt full` from gdb.

**Comment by fanglingsu** [comment] 2018-05-29 07:11
@crypt17 Strange, now it's a SIGUSR1? Can you provide a full abcktrace `bt full`. For now this looks similar to https://bugs.webkit.org/show_bug.cgi?id=168699 which is already fixed.

**Comment by crypt17** [comment] 2018-05-29 22:26
bt full
#0  0x00007ffff19295d9 in __GI___poll (fds=0x5555558de1a0, nfds=4, timeout=10873)
    at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff1c43439 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff1c437d2 in g_main_loop_run ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4dd2e85 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x000055555556c750 in main (argc=1, argv=0x7fffffffe288) at main.c:1915
        c = 0x55555581c0b0
        err = 0x0
        pidstr = 0x55555579edc0 "/home/crypt"
        winid = 0x0
        ver = 0
        buginfo = 0
        opts = 
            {{long_name = 0x5555555748fc "embed", short_name = 101 'e', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x7fffffffe150, description = 0x555555574908 "Reparents to window specified by xid", arg_description = 0x0}, {long_name = 0x5555555746d7 "config", short_name = 99 'c', flags = 0, arg = G_OPTION_ARG_FILENAME, arg_data = 0x55555577a9c0 <vb+32>, description = 0x55555557492d "Custom configuration file", arg_description = 0x0}, {long_name = 0x555555574947 "profile", short_name = 112 'p', flags = 0, arg = G_OPTION_ARG_CALLBACK, arg_data = 0x55555556c2af <profileOptionArgFunc>, description = 0x55555557494f "Profile name", arg_description = 0x0}, {long_name = 0x55555557495c "version", short_name = 118 'v', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7fffffffe14c, description = 0x555555574964 "Print version", arg_description = 0x0}, {long_name = 0x555555574972 "bug-info", short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x7fffffffe148, description = 0x55555557497b "Print used library versions", arg_description = 0x0}, {long_name = 0x0, short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}

**Comment by fanglingsu** [comment] 2018-05-30 20:01
@crypt17 This is really short and does not look like a segfault. Are you sure that vimb crashed?

**Comment by crypt17** [comment] 2018-05-30 22:26
I thinik that my rashing issue may have been resolved but an update on the system as it doesn't seem to be crashing now.

**Comment by fanglingsu** [comment] 2018-06-01 14:31
@crypt17 Nice to hear that. I close this issue for now. If vimb still crashes, feel free to reopen this issue.

**Closed by fanglingsu** 2018-06-01 14:31 UTC

**Comment by crypt17** [comment] 2018-06-01 23:52
Will do and thanks for all the help
