### ISSUE TITLE
Segmentation Fault on http://piwik.org

### ISSUE THREAD

**Issue by cmkarlsson** [fanglingsu/vimb#210] opened 2015-05-12 10:33 UTC
Browsing to http://piwik.org gives segmentation fault.

Running vimb 2.9 on Ubuntu 14.04
```console
% uname -a
Linux littledevil 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Steps to reproduce: 
``` console
$ git checkout -b t2.9 2.9 # Checkout 2.9 release
$ make GTK=3
$ ./vimb
:set scripts=false
:set plugins=false
:o http://piwik.org
[hit space]
segmentation fault (core dumped)
```

gdb tells me:
```console
Program received signal SIGSEGV, Segmentation fault.
0x00007fffeaccf185 in ?? () from /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
```

**Comment by fanglingsu** [comment] 2015-05-13 18:16
Sorry for the late response. I can't reproduce this issue with vimb 2.9 and built against gtk3. Can you provide a stacktrace of the issue?

- Does this happen only on piwik.org or also on all other pages?
- Can you please try to start vimb with an empty config file? Does this also
  segfault? There are at least two segfaults fixed in between 2.9 and current master cb48fe6 and ed5f069. So could you please try to reproduce the issue with the master branch?

**Comment by cmkarlsson** [comment] 2015-05-13 22:18
Reproduced in master 4f9e8f4. I've only tested on Ubuntu 14.04 but can reproduce on two separate machines.  gtk2 gives the same.

`:set images=false` stops vimb from crashing.

* Only encountered on piwik.org. I did a simplistic test where I scraped the images from the site and opened them in vimb one by one but that didn't cause any crashes.
* Still segfaults with empty config (I removed the ~/.config/vimb directory)


Stacktrace: (Assuming I've done this right otherwise please give me a pointer to what I need to do)
```
vimb [master●] » gdb ./src/vimb                                                                                       
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./src/vimb...done.
(gdb) run
Starting program: /home/martink/martin/git/vimb/src/vimb 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe4e3a700 (LWP 23083)]
[New Thread 0x7fffdffff700 (LWP 23084)]
[New Thread 0x7fff9f7fc700 (LWP 23085)]
[New Thread 0x7fff9e308700 (LWP 23086)]
[New Thread 0x7fff9cdb5700 (LWP 23087)]
[New Thread 0x7fff97fff700 (LWP 23088)]
[New Thread 0x7fff977fe700 (LWP 23089)]
[New Thread 0x7fff96958700 (LWP 23090)]
[New Thread 0x7fff96055700 (LWP 23091)]
[New Thread 0x7fff95854700 (LWP 23092)]
[New Thread 0x7fff95053700 (LWP 23093)]
[New Thread 0x7fff73fff700 (LWP 23094)]
[New Thread 0x7fff737fe700 (LWP 23095)]
[New Thread 0x7fff72ffd700 (LWP 23096)]
[Thread 0x7fff737fe700 (LWP 23095) exited]
[Thread 0x7fff95053700 (LWP 23093) exited]
[Thread 0x7fff96055700 (LWP 23091) exited]
[Thread 0x7fff73fff700 (LWP 23094) exited]
[Thread 0x7fff95854700 (LWP 23092) exited]
[New Thread 0x7fff95854700 (LWP 23097)]
[New Thread 0x7fff73fff700 (LWP 23098)]
[New Thread 0x7fff96055700 (LWP 23099)]
[Thread 0x7fff977fe700 (LWP 23089) exited]
[New Thread 0x7fff977fe700 (LWP 23100)]
[New Thread 0x7fff95053700 (LWP 23101)]
[New Thread 0x7fff727fc700 (LWP 23102)]
[New Thread 0x7fff71ffb700 (LWP 23103)]
[New Thread 0x7fff717fa700 (LWP 23104)]
[New Thread 0x7fff70ff9700 (LWP 23105)]

Program received signal SIGSEGV, Segmentation fault.
sse2_blt (src_bits=<optimized out>, dst_bits=<optimized out>, src_stride=<optimized out>, dst_stride=<optimized out>, 
    src_bpp=<optimized out>, src_x=<optimized out>, src_y=0, dest_x=0, dest_y=dest_y@entry=0, width=width@entry=1018, 
    height=<optimized out>, height@entry=411, dst_bpp=<optimized out>, imp=<optimized out>)
    at ../../pixman/pixman-sse2.c:4763
4763	../../pixman/pixman-sse2.c: No such file or directory.
(gdb) backtrace
#0  sse2_blt (src_bits=<optimized out>, dst_bits=<optimized out>, src_stride=<optimized out>, 
    dst_stride=<optimized out>, src_bpp=<optimized out>, src_x=<optimized out>, src_y=0, dest_x=0, 
    dest_y=dest_y@entry=0, width=width@entry=1018, height=<optimized out>, height@entry=411, dst_bpp=<optimized out>, 
    imp=<optimized out>) at ../../pixman/pixman-sse2.c:4763
#1  0x00007fffeaccf3ab in sse2_blt (height=411, width=1018, dest_y=0, dest_x=<optimized out>, src_y=<optimized out>, 
    src_x=<optimized out>, dst_bpp=<optimized out>, src_bpp=<optimized out>, dst_stride=<optimized out>, 
    src_stride=<optimized out>, dst_bits=<optimized out>, src_bits=<optimized out>, imp=<optimized out>)
    at ../../pixman/pixman-sse2.c:4819
#2  sse2_composite_copy_area (imp=<optimized out>, info=<optimized out>) at ../../pixman/pixman-sse2.c:4812
#3  0x00007fffeac4a841 in pixman_image_composite32 (op=op@entry=PIXMAN_OP_SRC, src=src@entry=0xaa39b0, 
    mask=mask@entry=0x0, dest=dest@entry=0xb79ed0, src_x=0, src_y=0, mask_x=0, mask_y=0, dest_x=0, dest_y=0, 
    width=1018, height=411) at ../../pixman/pixman.c:707
#4  0x00007ffff15b0e49 in composite_boxes (_dst=<optimized out>, op=CAIRO_OPERATOR_SOURCE, 
    abstract_src=<optimized out>, abstract_mask=<optimized out>, src_x=0, src_y=0, mask_x=0, mask_y=0, dst_x=0, 
    dst_y=0, boxes=0x7fffffffaff0, extents=0x7fffffffb2ac)
    at /build/buildd/cairo-1.13.0~20140204/src/cairo-image-compositor.c:532
#5  0x00007ffff15e7caa in composite_aligned_boxes (boxes=0x7fffffffaff0, extents=0x7fffffffb270, 
    compositor=0x7ffff1889020 <spans>) at /build/buildd/cairo-1.13.0~20140204/src/cairo-spans-compositor.c:683
#6  clip_and_composite_boxes (compositor=compositor@entry=0x7ffff1889020 <spans>, 
    extents=extents@entry=0x7fffffffb270, boxes=boxes@entry=0x7fffffffaff0)
    at /build/buildd/cairo-1.13.0~20140204/src/cairo-spans-compositor.c:882
#7  0x00007ffff15e809e in clip_and_composite_boxes (compositor=0x7ffff1889020 <spans>, extents=0x7fffffffb270, 
    boxes=0x7fffffffaff0) at /build/buildd/cairo-1.13.0~20140204/src/cairo-spans-compositor.c:901
#8  0x00007ffff15e8186 in _cairo_spans_compositor_paint (_compositor=0x7ffff1889020 <spans>, extents=0x7fffffffb270)
    at /build/buildd/cairo-1.13.0~20140204/src/cairo-spans-compositor.c:983
#9  0x00007ffff15a6899 in _cairo_compositor_paint (compositor=0x7ffff1889020 <spans>, surface=0xbf4300, 
    op=<optimized out>, source=<optimized out>, clip=<optimized out>)
    at /build/buildd/cairo-1.13.0~20140204/src/cairo-compositor.c:65
#10 0x00007ffff15eb051 in _cairo_surface_paint (surface=0xbf4300, op=CAIRO_OPERATOR_SOURCE, source=0x7fffffffb620, 
    clip=0x0) at /build/buildd/cairo-1.13.0~20140204/src/cairo-surface.c:2081
#11 0x00007ffff1616aaf in surface_source (src_y=0x7fffffffb75c, src_x=0x7fffffffb758, sample=<optimized out>, 
    extents=<optimized out>, is_mask=0, pattern=0x7fffffffc740, dst=0x98ce90)
    at /build/buildd/cairo-1.13.0~20140204/src/cairo-xlib-source.c:1033
#12 _cairo_xlib_source_create_for_pattern (_dst=0x98ce90, pattern=0x7fffffffc740, is_mask=0, extents=<optimized out>, 
    sample=<optimized out>, src_x=0x7fffffffb758, src_y=0x7fffffffb75c)
    at /build/buildd/cairo-1.13.0~20140204/src/cairo-xlib-source.c:1141
#13 0x00007ffff15fc923 in clip_and_composite (compositor=compositor@entry=0x7ffff188a320 <compositor>, 
    extents=extents@entry=0x7fffffffc6c0, draw_func=draw_func@entry=0x7ffff15faee0 <composite_traps>, 
    mask_func=mask_func@entry=0x0, draw_closure=draw_closure@entry=0x7fffffffba10, need_clip=0)
    at /build/buildd/cairo-1.13.0~20140204/src/cairo-traps-compositor.c:1024
#14 0x00007ffff15fd9df in clip_and_composite_polygon (compositor=compositor@entry=0x7ffff188a320 <compositor>, 
    extents=extents@entry=0x7fffffffc6c0, polygon=polygon@entry=0x7fffffffbe80, antialias=CAIRO_ANTIALIAS_DEFAULT, 
    fill_rule=CAIRO_FILL_RULE_EVEN_ODD, curvy=curvy@entry=0)
    at /build/buildd/cairo-1.13.0~20140204/src/cairo-traps-compositor.c:1602
#15 0x00007ffff15fd3f3 in clip_and_composite_boxes (compositor=compositor@entry=0x7ffff188a320 <compositor>, 
    extents=extents@entry=0x7fffffffc6c0, boxes=boxes@entry=0x7fffffffc2a0)
    at /build/buildd/cairo-1.13.0~20140204/src/cairo-traps-compositor.c:1776
#16 0x00007ffff15fe077 in _cairo_traps_compositor_fill (_compositor=0x7ffff188a320 <compositor>, 
    extents=0x7fffffffc6c0, path=0xbfe4e8, fill_rule=CAIRO_FILL_RULE_WINDING, tolerance=0.10000000000000001, 
    antialias=CAIRO_ANTIALIAS_DEFAULT) at /build/buildd/cairo-1.13.0~20140204/src/cairo-traps-compositor.c:2237
#17 0x00007ffff15a6b27 in _cairo_compositor_fill (compositor=0x7ffff188a320 <compositor>, 
    surface=surface@entry=0x98ce90, op=op@entry=CAIRO_OPERATOR_OVER, source=source@entry=0x7fffffffcac0, 
    path=path@entry=0xbfe4e8, fill_rule=fill_rule@entry=CAIRO_FILL_RULE_WINDING, tolerance=0.10000000000000001, 
    antialias=antialias@entry=CAIRO_ANTIALIAS_DEFAULT, clip=clip@entry=0xa87900)
    at /build/buildd/cairo-1.13.0~20140204/src/cairo-compositor.c:203
#18 0x00007ffff1617ee8 in _cairo_xlib_surface_fill (_surface=<optimized out>, op=CAIRO_OPERATOR_OVER, 
    source=0x7fffffffcac0, path=0xbfe4e8, fill_rule=CAIRO_FILL_RULE_WINDING, tolerance=<optimized out>, 
    antialias=CAIRO_ANTIALIAS_DEFAULT, clip=0xa87900)
    at /build/buildd/cairo-1.13.0~20140204/src/cairo-xlib-surface.c:1646
#19 0x00007ffff15eb504 in _cairo_surface_fill (surface=0x98ce90, op=CAIRO_OPERATOR_OVER, source=0x7fffffffcac0, 
    path=0xbfe4e8, fill_rule=CAIRO_FILL_RULE_WINDING, tolerance=0.10000000000000001, 
    antialias=CAIRO_ANTIALIAS_DEFAULT, clip=0xa87900) at /build/buildd/cairo-1.13.0~20140204/src/cairo-surface.c:2305
#20 0x00007ffff15ae58c in _cairo_gstate_fill (gstate=0xa41ee0, path=path@entry=0xbfe4e8)
    at /build/buildd/cairo-1.13.0~20140204/src/cairo-gstate.c:1317
#21 0x00007ffff15a80d9 in _cairo_default_context_fill (abstract_cr=0xbfe180)
    at /build/buildd/cairo-1.13.0~20140204/src/cairo-default-context.c:1055
#22 0x00007ffff15a19f5 in cairo_fill (cr=0xbfe180) at /build/buildd/cairo-1.13.0~20140204/src/cairo.c:2205
#23 0x00007ffff6237b56 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#24 0x00007ffff6231f9f in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#25 0x00007ffff628fff7 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#26 0x00007ffff628b4a5 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#27 0x00007ffff69dfbd7 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#28 0x00007ffff69bd75c in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#29 0x00007ffff69cd6b5 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#30 0x00007ffff69cd8fa in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#31 0x00007ffff69cdc10 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#32 0x00007ffff6991e52 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#33 0x00007ffff697eb25 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#34 0x00007ffff698127a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#35 0x00007ffff6981562 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#36 0x00007ffff6981120 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#37 0x00007ffff6991e63 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#38 0x00007ffff697eb25 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#39 0x00007ffff6a3d664 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#40 0x00007ffff6a42482 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#41 0x00007ffff6a4edf6 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#42 0x00007ffff6a4fdc9 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#43 0x00007ffff6a516f2 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#44 0x00007ffff6a4ef10 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#45 0x00007ffff6a4fdc9 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#46 0x00007ffff6a516f2 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#47 0x00007ffff6a4ef10 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#48 0x00007ffff6a4fdc9 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#49 0x00007ffff6a5006e in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#50 0x00007ffff69059cd in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#51 0x00007ffff7017414 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#52 0x00007ffff61e50f3 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#53 0x00007ffff62ef201 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#54 0x00007ffff6307472 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#55 0x00007ffff3da1703 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#56 0x00007ffff3da0ce5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#57 0x00007ffff3da1048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#58 0x00007ffff3da130a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#59 0x00007ffff582ffe5 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#60 0x000000000041696c in main (argc=1, argv=0x7fffffffe8b8) at main.c:1829
```

**Comment by fanglingsu** [comment] 2015-05-15 18:24
Tank you for the trace. It does not look like a fault in vimb. Maybe this is the same like https://bugs.launchpad.net/midori/+bug/1415463.

> I did a simplistic test where I scraped the images from the site and opened them in vimb one by one but that didn't cause any crashes.

That's a nice idea, but note that image can be included also by css style sheets as elemnt backgorunds are somethings similar. Maybe we you can find the file that causes the crash. But it might also be some cairo iternal fault that could not be reproduced by a single rendered image or only if the image is going to be resized or so.

**Comment by cmkarlsson** [comment] 2015-05-17 21:55
Thanks. If there is nothing vimb can do about it you can close this and I'll try reproduce with underlying libraries and poke them instead. Cheers!

**Closed** 2015-05-23 18:55 UTC
