### ISSUE TITLE
Issue(s) with shortcuts, problem with # and |

### ISSUE THREAD

**Issue by aksr** [fanglingsu/vimb#159] opened 2015-01-21 20:58 UTC
Something like this doesn't work (#):
     shortcut-add gt=http://translate.google.com/#$0/$1/$2
  :open gt de en gesundheit
Also, if URL contains pipe symbol (|), for example:
     shortcut-add gte=http://translate.google.com/#auto|en|$0
http://translate.google.com/#auto|en|gesundheit
(variant with pipe symbol)
(Trying to escape # and/or | doesn't work.)

**Comment by fanglingsu** [comment] 2015-01-22 21:03
Strange, even when I type the url http://translate.google.com/#auto/en/gesundheit direct the part after the `#` is removed. I'll have a look to this soon. 
The pipe does not work because this is used to seperate commands from each other to allow things like `:set scripts!|normal r`. There are only few commands that do not end on pipe char.

**Comment by aksr** [comment] 2015-01-23 21:49
There are links with pipe symbol. The best compromise would be to change symbol for command separation. What about `;' or `,'? What do you think?

**Comment by The-Compiler** [comment] 2015-01-24 13:25
FWIW, others (like dwb, or my own qutebrowser) use `;;` (two chars). That shouldn't conflict with anything, and still is easy to remember.

**Comment by fanglingsu** [comment] 2015-01-24 18:49
@aksr I've never seen liks with pipe symbols in the wild. Can you provide an example? Links with pipes should work, because the are not processed as commands. The issues exists only for shortcuts,  and in case the uri is typed in the `:open` or `:tabopen` command or from history.
I don't want to change the seperator char. The syntax is leaned on vim and not dwb, so we use the same separator char. But it would be possible to skip seperator meaning of the pipe char for the open commands and shortcuts. But I've to think about the consequences of this change.

**Comment by fanglingsu** [comment] 2015-01-24 18:58
The  http://translate.google.com/#auto/en/gesundheit should work from what vimb does. The url is given to webkit, but some where the part after `#` is lost or ignored by google.

**Comment by fanglingsu** [comment] 2015-01-24 20:58
Vim treats the pipe for :edit command (that the equivalent to vimb it's `:open`) as command separator. But I can't fin any useful case to allow to appen another command after the `:open`. I've a look to pentadactyl, the other inspiration for vimb. Pentadactyl does not allow the pipe separator for `:open` and `:winopen` commands [pentadactyl][]. So I'll follow pentadactyl here and remove the special meaning of the pipe for those commands too.

[pentadactyl]: http://5digits.org/help/pentadactyl/cmdline.xhtml#cmdline-lines

**Comment by fanglingsu** [comment] 2015-01-26 19:49
@aksr Does the latest commit work for you?

**Comment by aksr** [comment] 2015-01-26 20:20
@fanglingsu Well, I cannot test it without **#** part. :)
Btw, link with pipes is google translate variant.

**Comment by fanglingsu** [comment] 2015-01-27 21:15
The google translate url does use `/` and not pipe if I use it, so the slash variant should work. And there is no issue with the `#` for me. But there is something else that google or the JavaScripts dont like so thet the location hash (part after the `#` in the uri) is removed by them.
I could open your translate uri after I changed the user agent some times and toggled some other settings in vimb, but I can't reproduce this. But I assume that this issue is related to the user agent string vimb sends. There where multiple issues in the last months with google and the user agent string.

**Comment by fanglingsu** [comment] 2015-01-27 21:23
OK, I think I got it. Your uri is http but google wants to use https and sends back HTTP 302 with new location as https. And during this redirect vimb or webkit looses the location hash of the uri.
you should use https for the shortcut as a quick fix until we have a better solution.

**Comment by fanglingsu** [comment] 2015-01-27 22:04
The issue is a long known bug in webkit [24175](https://bugs.webkit.org/show_bug.cgi?id=24175). So wen can't fix it in vimb and close the issue.

**Closed by fanglingsu** 2015-01-27 22:04 UTC
Labels: bug

**Comment by aksr** [comment] 2015-01-27 22:26
Strange. Anyway, thank you for your effort!
