### ISSUE TITLE
Input mode and command mode mix up after going back in history

### ISSUE THREAD

**Issue by ghost** [fanglingsu/vimb#214] opened 2015-05-17 07:37 UTC
Under some conditions, vimb interprets attempts to edit web input fields as commands.

To reproduce:
1) Open duckduckgo.com or any search engine
2) Search for any term and click on any result
3) Go back to the search page pressing CTRL-O
4) Place cursor on the search engine's input field

Expected result:
Vimb should go in input mode and allow the user to type in another search.

Actual result:
Vimb allows the user to type in another search as long as the key is not bound to a vimb command. If the key is bound, vimb will execute the bound action. For example, attempting to type "r" will reload the page.

**Comment by fanglingsu** [comment] 2015-05-17 18:48
Tank you for this bug report. I can reproduce this, but may be it will take some weeks to fix this. There where a lot of input switching related issue in history of vimb and finxing one might generate a regression on some other page.
We had previously multiple parts in the code that where responsible to switch vimb int inputmode if a editable element was clicket or hinted. But the warious parts did their job different. Now there is only one place for the locig of switching it input mode. This is set as dom observer on that is added on the webviews `onload-event`.
I think the main problem is that the onload event isn't called in case vimb go back in history. There must be used some other event instead.

**Comment by fanglingsu** [comment] 2015-05-17 18:52
If I use a static page without fancy JavaScript with input element and leave this and go back sith `Ctrl-O` this switching to input mode on click works pretty fine.
I can't reproduce the issue if I disable page chache by `:set pagecache=0`, can you confirm this?

**Comment by scrzbble** [comment] 2015-05-17 22:06
It does not make a difference here whether I use java or not. I tried searching from https://duckduckgo.com/html and I still get the input/command bug.

However, I can confirm that disabling caching is a workaround.

**Comment by shioyama** [comment] 2015-07-26 00:45
I'm noticing this issue as well. Turning off caching for now but would be great to get a proper fix for it. (Vimb is great otherwise, thanks for all your work on this!)

**Comment by shioyama** [comment] 2015-10-22 22:30
@scrzbble #246 is merged now, if you have a chance could you try the latest vimb and confirm that it fixes the problem?

**Comment by fanglingsu** [comment] 2017-02-28 22:47
Seems to be fixed.

**Closed by fanglingsu** 2017-02-28 22:47 UTC
Labels: bug
