### ISSUE TITLE
Search highlighting graphics glitch

### ISSUE THREAD

**Issue by antoyo** [fanglingsu/vimb#291] opened 2016-08-31 12:58 UTC
Hello.
When I do a search within `vimb`, I cannot see the text on the same line as the currently highlighted word.
See the attached screenshot to see what I mean:
![img-2016-08-31-085139](https://cloud.githubusercontent.com/assets/584972/18129498/02efcc0e-6f59-11e6-88bf-a52e6c1baaaf.png)
I use the i3 window manager without compositing (I don't know if it is related).
Thanks to fix this issue.

**Comment by fanglingsu** [comment] 2016-08-31 22:03
I use archlinux and noticed that too, since about a month ago. I assume that this is a font rendering issue and we can't do anything from within vimb to change this.
I can reproduce it when i start a search. The glitch disappears for me, when I stop the search by `<Esc>` and resume it by `n` or `N`.

**Comment by Nicop06** [comment] 2016-10-02 00:06
I have this problem for a while too, on both `gentoo` and `ArchLinux`. I thing I also had the problem in [luakit](https://github.com/luakit/luakit), and I definitely have it in [surf](http://surf.suckless.org). This might come from webkit-gtk rendering engine. I will try to investigate more about the origin of the problem as this is one of the main reason I don't use vimb more often (that and the fact I'm too lazy to configure tabbed and my password manager).

**Comment by fanglingsu** [comment] 2016-10-03 19:35
Thank you for helping here. I do not have as many time to dig into this, and I also don't have any glue where to start to investigate the issue. I hope there will be more developers spendng time to bump the webkit2 port of vimb into a usable state.

**Comment by antoyo** [comment] 2016-10-03 19:39
Webkit2 has the same issue.

**Comment by fanglingsu** [comment] 2017-06-22 12:22
I have not seen this for some time now. @antoyo Do you still get this glitch?

**Comment by antoyo** [comment] 2017-06-22 13:34
I've just tested and still see the same issue.
However, it is a webkit2gtk bug, not a vimb bug, so we can close this issue.
I'll open an issue on the webkit2gtk bug tracker, but don't expect this to be fixed soon.

**Comment by fanglingsu** [comment] 2017-06-23 21:57
@antoyo OK, then we close this.

**Closed by fanglingsu** 2017-06-23 21:57 UTC

**Comment by antoyo** [comment] 2017-06-24 11:56
I reported the issue [here](https://bugs.webkit.org/show_bug.cgi?id=173809).
