### ISSUE TITLE
Incorrect urlbar string when on a bad page

### ISSUE THREAD

**Issue by b80905** [fanglingsu/vimb#224] opened 2015-07-16 15:32 UTC
If you open a nonexistent web address, the URL bar is not updated and the URL of
the previous page is displayed instead.

**Comment by fanglingsu** [comment] 2015-07-16 20:19
I can reproduce this behaviour. But what do you think should be shown in url bar instead, the uri that does could not be loaded, 'about:blank' or nothing?

**Comment by fanglingsu** [comment] 2015-07-16 20:44
Can you please check if the issue is fixed for you too?

**Comment by b80905** [comment] 2015-07-17 06:49
Not quite.
If you press f and then ESC on a nonexistent page, the URL of the
previous page is shown again.
If you open a nonexistent page and then another nonexistent one and
press CTRL+O, then the title of the previous page is displayed in the
title bar.

Of course the URL that couldn't be loaded should be shown.

**Comment by fanglingsu** [comment] 2015-07-17 11:31
You're right. I think the fix would take some time more, because this is webkit default behaviour. If a page could not be loaded the webview object contains the old uri and the old title. So we have to do some more internal logic for the title and current uri here.

**Comment by fanglingsu** [comment] 2015-07-17 12:20
So, another approach to fet rid of this issue. We'll see if this introduces some regression somewhere else.

**Comment by fanglingsu** [comment] 2015-07-23 14:56
This should be fixed now.

**Closed by fanglingsu** 2015-07-23 14:56 UTC
Labels: bug
