### ISSUE TITLE
Local files are downloaded instead of rendered

### ISSUE THREAD

**Issue by Artymort** [fanglingsu/vimb#456] opened 2017-11-13 17:48 UTC
It would seem that I can't re-open issue #264 so I'm opening a new one.

Issue: local `html` files are downloaded instead of rendered.

How (I) can reproduce:
```bash
git clone https://github.com/fanglingsu/vimb
cd vimb ; make ; cd src
touch empty
```

From here,
* `echo "content" | pandoc -t html5 -s | ./vimb -c empty -` works
* `echo "content" | pandoc -t html5 -s > tmp.html ; ./vimb -c empty tmp.html` downloads the file
* `echo "content" | pandoc -t html5 -s > tmp.html ; ./vimb -c empty "file://<full_path>/tmp.html"` downloads the file

Debug infos:
```
./vimb --bug-info
Commit:          3.0-alpha-65-gee984e6
WebKit compile:  2.18.3
WebKit run:      2.18.3
GTK compile:     3.22.26
GTK run:         3.22.26
libsoup compile: 2.60.2
libsoup run:     2.60.2
Extension dir:   /usr/local/lib/vimb
```

**Comment by steview2000** [comment] 2018-04-20 13:52
I have exactly the same problem. Surprisingly I don't have the problem with on another computer with the same operating system and the same vimb system installed.

I checked, the problem appears in similar minimalistic webkit based browsers, namely surf and uzbl.

**Comment by fanglingsu** [comment] 2018-04-20 21:16
@Artymort Thank you for you detailed issue report. Can't reproduce this. I've tested it with the _tests/manual/hints.html_ out of the project.

@steview2000 Hope you'll help us diggin into this issue. Could you please check which mime-type the systems assume `file -bi file.html`? I get `text/html; charset=us-ascii`.

**Comment by steview2000** [comment] 2018-04-24 20:58
@fanglingsu 
Hi. First of all, when I run the test examples by @Artymort, they surprisingly all work for me. 

In my case a certain statement at the beginning of the file causes problems. A file noworks.html with following lines will be downloaded:

`
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
<head>
</head>
 <body>
    Some text
 </body>
</html>
`

A file works.html with the following html-code will be executed:
`
<!DOCTYPE html PUBLIC>
<html>
<head>
</head>
 <body>
    Some text
 </body>
</html>
`

downloads the file.

For the sake of completeness:
`
vimb --bug-info

`Commit:          3.1.0-6-g1b85f0d
WebKit compile:  2.18.6
WebKit run:      2.18.6
GTK compile:     3.22.11
GTK run:         3.22.11
libsoup compile: 2.56.0
libsoup run:     2.56.0
Extension dir:   /usr/local/lib/vimb

**Comment by fanglingsu** [comment] 2018-04-25 22:16
@steview2000 Thank you for your testing. But it keeps strange. I still can't reproduce this with the xhtml doc typed sample file. It might be related to some quirks mode in webkit https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode. But also enabling `set site-specific-quirks=on` caused no download on m machine.

**Comment by steview2000** [comment] 2018-04-26 21:25
@fanglingsu 
You were right. The problem had something to do with the mime-type. The problem even occured with Midori (another webkit Browser). There, the mime-type was shown as applications/x-extensions-html.
I deleted my whole ~/.local/share/mime folder and the problem is solved.

**Comment by fanglingsu** [comment] 2018-04-27 21:10
@steview2000 Nice to head that it works for you now.

**Comment by fanglingsu** [comment] 2018-06-14 21:30
I close this, because the issue seems to be not part of vimb.

**Closed by fanglingsu** 2018-06-14 21:30 UTC
