### ISSUE TITLE
Markup files are shown as plain text, not rendered

### ISSUE THREAD

**Issue by chairmank** [fanglingsu/vimb#319] opened 2017-01-20 05:07 UTC
I am running release 2.11.

I want to open a HTML file `/tmp/test.html` with contents:

```
<!doctype html>
<html>
  <body>
    This is a test.
  </body>
</html>
```

When I load this file through STDIN

```
cat /tmp/test.html | vimb -
```

it renders as expected. However, if I do

```
vimb /tmp/test.html
```

or

```
vimb file:///tmp/test.html
```

then I see the source as plain text, not the rendered document. I also see this behavior when I run the command

```
:o file:///tmp/test.html
```

**Comment by chairmank** [comment] 2017-01-20 05:07
Could this be related to https://github.com/fanglingsu/vimb/issues/264 ?

**Comment by chairmank** [comment] 2017-01-20 05:30
There must be a difference in behavior between `webkit_web_view_load_string` and `webkit_web_view_load_uri`.

**Comment by fanglingsu** [comment] 2017-01-20 19:26
That sounds strange. I thought webkit will do some magic on the file extension to guess how this should be rendered. I'm not on my computer, so I can't test if I can reproduce this issue today.

**Comment by fanglingsu** [comment] 2017-02-28 23:08
This issue seems to be sticket to webkit1. So I close this in hope the webkit2 branch will be ready for work soon.

**Closed by fanglingsu** 2017-02-28 23:08 UTC
