### ISSUE TITLE
:quit slow?

### ISSUE THREAD

**Issue by sdothum** [fanglingsu/vimb#161] opened 2015-02-03 19:40 UTC
I am running vimb with *tabbed* and have "d" keybind to ":quit" to match the close tab character of other vim-like browsers. :quit seems slow (when compared to the close tab of other browsers) -- probably due to the housekeeping that goes on (:quit! doesn't appear any faster).

Not a deal breaker but :quit is definitely slower than closing the window containing vimb -- which I was doing before using vimb with *tabbed*.

On the subject of lag.. is there a way to speed up history searches. I've ported over a rather large luakit history (30K records) which takes a few seconds to search (compared to the near instantaneous dmenu search of the same database which includes converting it from sqlite first!). Again, not a deal breaker.. and it does beckon the utility of such potentially stale dated information!

**Comment by fanglingsu** [comment] 2015-02-03 21:32
If you are using the large 30K history file, the slow `:quit` is caused by the housekeeping, like you called it. The process at the moment reads all existing history entries and remove duplicates and write all record back to the history files. This will take a while for such a large history.

The history lookup takes the file and removes duplicates and filters them by the contents that are already in the inpubox written. So dmenu is faster because it does not remove duplicates.

I must admit that I use only a small history with about thousand record so I never ran into such an issue, but I hope we can find a better solution to implement the history. Vimprobable checks uniqueness on every inserted record (each opened page), which causes a lot of file operatoins but you don't need to cleanup the history on quit. Vimb writes everything to the end of the history file and do the cleanup on quit.

**Comment by sdothum** [comment] 2015-02-03 22:18
Thank you again for the explanation. Removing duplicates is a good thing so I can't complain about that! The more I use vimb -- and it has only been days -- the more I appreciate the work you have put into it. It's the vim'iest of the browsers I have used and I'm lovin' it! Keep up the good work!

**Comment by sdothum** [comment] 2015-02-05 02:28
Just an update: I wrote a simple wrapper for "tabbed vimb" which, on launch initializs the history file to the last 1000 records, retaining the remainder for dmenu archival history search. Lag is now non-existant for history searches and vimb instance (tab) closures. Happy camper here!

**Comment by fanglingsu** [comment] 2015-02-05 14:40
OK, nice to hear, that you found a way to speed up vimb. I close the issue, but I added and enhancement issue so that we don't forget to improve the way vimb handles the history completion and cleanup.

**Closed by fanglingsu** 2015-02-05 14:40 UTC

**Comment by fanglingsu** [comment] 2015-02-06 23:04
@sdothum Can you please check the latest commit 640d309 with your large history file. This uses a hash table to check for duplicates in the history. My history is not large enought to do a real check if this workes better.

**Comment by sdothum** [comment] 2018-04-18 15:46
Never came back to this issue thread after it was closed and just noticed it. Your request is dated.. would you still like me to test your history hashing?

**Comment by fanglingsu** [comment] 2018-04-18 20:13
I assume this will have fixed the slow quit. Nobody else issued such a slow quite in tha last three years.
