### ISSUE TITLE
Character in input mode sometimes not entered.

### ISSUE THREAD

**Issue by JJK96** [fanglingsu/vimb#471] opened 2018-01-11 09:48 UTC
### Steps to reproduce
I noticed this bug on google drive today, I remember that it also happened on another website, but I do not know which at the moment.

Try to edit the name of a document, try to enter an "r".

### Expected behaviour

The r is entered into the input box.

### Actual behaviour
The browser switches to input mode, but the "r" key is not passed. Even in passthrough mode the "r" key cannot be entered.

**Comment by fanglingsu** [comment] 2018-01-11 12:20
@JJK96 I do not use google drive so it would be nice if you can find another page where this issue appears too.

**Comment by JJK96** [comment] 2018-01-11 13:19
I was afraid so, I cannot find another site where this problem happens, and I noticed that resetting to the default user-agent resolved this. So I am sorry for bothering you with this.

**Comment by mlopes** [comment] 2018-04-26 12:34
I've seen this before, when writing in some forms sometimes even though I'm in input mode it receives the character as a vimb command as if it was in normal mode. Right now I could only reproduce it in google products as well, I'll post it here if I manage to see it anywhere else.

**Comment by fanglingsu** [comment] 2018-04-27 23:00
@mlopes Could you try if you can enter the chars when you use the PASS THROUGH mode activated by `CTRL-Z`?

**Comment by mlopes** [comment] 2018-04-30 12:27
CTRL-Z seems to work as expected, hadn't thought of trying that, thanks. :)

**Comment by fanglingsu** [comment] 2018-04-30 21:35
OK. Seems to be a bug of google or the interpretion of the given user agent string. Or if it's not related to the user agent string, it could be avoided using PASS THROUGH mode. So I close this issue. Please feel free, to open it again, if it's a fault in vimb.

**Closed by fanglingsu** 2018-04-30 21:35 UTC
